# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 703fafbed5e1d54309c2903291372385c42b3e36c6033b68592f69115831493bbf74123dbf9600b004143ee1e7568fafa86eba3434fcbdc3c74d7960d9f2bea0
  email_provider_username: <%= ENV['EMAIL_PROVIDER_USERNAME'] || 'steve.bi@gmail.com' %>
  email_provider_password: <%= ENV['EMAIL_PROVIDER_PASSWORD'] || 'Yang!234' %>
  mailchimp_api_key: <%= ENV['MAILCHIMP_API_KEY'] || '17451ff4fd2396835f0ca9fd8d039569-us10' %>
  mailchimp_list_id: <%= ENV['MAILCHIMP_LIST_ID'] || '5af1f16781' %>
  domain_name: <%= ENV['DOMAIN_NAME'] || 'example.com' %>
  ower_email: <%= ENV['OWNER_EMAIL'] || 'steve.bi@gmail.com' %>      
test:
  secret_key_base: 394004650b7a856150815916f3c70ad90a8f668de202a36b08adf4016255ad286103a907be7005dc8b1acd5924ffb45b0959e5c9fd3c09ddba8444fb36d6c1b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
